In [1]:
import pandas as pd

In [9]:
import os
os.listdir()

['-1.14-windows.xml',
 '.anaconda',
 '.arduinoIDE',
 '.bash_history',
 '.cache',
 '.codex',
 '.conda',
 '.condarc',
 '.config',
 '.continuum',
 '.git-for-windows-updater',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.m2',
 '.matplotlib',
 '.nbi',
 '.packettracer',
 '.streamlit',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'anaconda_projects',
 'app.py',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 9.0.0',
 'Contacts',
 'Cookies',
 'data_cleaning_customer.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'label_encoder.pkl',
 'Links',
 'Local Settings',
 'marketing_campaign-selected-columns.csv',
 'Mithali0603-HelloWorld',
 'model.pkl',
 'Music',
 'My Documents',
 'NetHood',
 'notebook.html',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TM.blf',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TM.blf.cnpf',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{71d54c77-e616-11ef-ab2e-005056c00008}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PyCharmMiscProject',
 'PycharmProjects',
 'Recent',
 'Resume.csv',
 'resume_training.ipynb.ipynb',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'TASH.ipynb',
 'task phn tech.ipynb',
 'task phn-Copy1.ipynb',
 'task phn.ipynb',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'untitled1.txt',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'vectorizer.pkl',
 'Videos',
 'VirtualBox VMs',
 'website editing ,.txt',
 'website editing.html',
 'website.html',
 'WPS Cloud',
 'WPS Cloud Files',
 'WPSDrive']

In [10]:
df = pd.read_csv("marketing_campaign-selected-columns.csv")
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173

In [11]:
pd.set_option('display.max_columns', None)

In [12]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173

In [13]:
pd.set_option('display.max_rows', None)

In [14]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,520
6,965,1971,Graduation,Divorced,55635.0,0,1,13-11-2012,34,235
7,6177,1985,PhD,Married,33454.0,1,0,08-05-2013,32,76
8,4855,1974,PhD,Together,30351.0,1,0,06-06-2013,19,14
9,5899,1950,PhD,Together,5648.0,1,1,13-03-2014,68,28
10,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5
11,387,1976,Basic,Married,7500.0,0,0,13-11-2012,59,6
12,2125,1959,Graduation,Divorced,63033.0,0,0,15-11-2013,82,194
13,8180,1952,Master,Divorced,59354.0,1,1,15-11-2013,53,233
14,2569,1987,Graduation,Married,17323.0,0,0,10-10-2012,38,3
15,2114,1946,PhD,Single,82800.0,0,0,24-11-2012,23,1006
16,9736,1980,Graduation,Married,41850.0,1,1,24-12-2012,51,53
17,4939,1946,Graduation,Together,37760.0,0,0,31-08-2012,20,84
18,6565,1949,Master,Married,76995.0,0,1,28-03-2013,91,1012
19,2278,1985,2n Cycle,Single,33812.0,1,0,03-11-2012,86,4
20,9360,1982,Graduation,Married,37040.0,0,0,08-08-2012,41,86
21,5376,1979,Graduation,Married,2447.0,1,0,06-01-2013,42,1
22,1993,1949,PhD,Married,58607.0,0,1,23-12-2012,63,867
23,4047,1954,PhD,Married,65324.0,0,1,11-01-2014,0,384
24,1409,1951,Graduation,Together,40689.0,0,1,18-03-2013,69,270
25,7892,1969,Graduation,Single,18589.0,0,0,02-01-2013,89,6
26,2404,1976,Graduation,Married,53359.0,1,1,27-05-2013,4,173
27,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5
28,9422,1989,Graduation,Married,38360.0,1,0,31-05-2013,26,36
29,1966,1965,PhD,Married,84618.0,0,0,22-11-2013,96,684
30,6864,1989,Master,Divorced,10979.0,0,0,22-05-2014,34,8
31,3033,1963,Master,Together,38620.0,0,0,11-05-2013,56,112
32,5710,1970,Graduation,Together,40548.0,0,1,10-10-2012,31,110
33,7373,1952,PhD,Divorced,46610.0,0,2,29-10-2012,8,96
34,8755,1946,Master,Married,68657.0,0,0,20-02-2013,4,482
35,10738,1951,Master,Single,49389.0,1,1,29-08-2013,55,40
36,4339,1970,PhD,Married,67353.0,0,1,31-12-2013,37,702
37,10755,1976,2n Cycle,Married,23718.0,1,0,02-09-2013,76,6
38,8595,1973,Graduation,Widow,42429.0,0,1,11-02-2014,99,55
39,2968,1943,PhD,Divorced,48948.0,0,0,01-02-2013,53,437
40,8601,1980,Graduation,Married,80011.0,0,1,29-04-2013,3,421
41,503,1985,Master,Married,20559.0,1,0,12-03-2013,88,13
42,8430,1957,Graduation,Together,21994.0,0,1,24-12-2012,4,9
43,7281,1959,PhD,Single,NaN,0,0,05-11-2013,80,81
44,2139,1975,Master,Married,7500.0,1,0,02-10-2013,19,3
45,1371,1976,Graduation,Single,79941.0,0,0,28-06-2014,72,123
46,9909,1996,2n Cycle,Married,7500.0,0,0,09-11-2012,24,3
47,7286,1968,Graduation,Together,41728.0,1,0,24-05-2013,92,13
48,7244,1951,Graduation,Single,NaN,2,1,01-01-2014,96,48
49,6566,1954,PhD,Married,72550.0,1,1,08-11-2012,39,826
50,8614,1957,Graduation,Widow,65486.0,0,1,12-05-2014,29,245
51,4114,1964,Master,Married,79143.0,0,0,11-08-2012,2,650
52,1331,1977,Graduation,Single,35790.0,1,0,02-01-2013,54,12
53,2225,1977,Graduation,Divorced,82582.0,0,0,07-06-2014,54,510
54,9381,1978,Graduation,Married,66373.0,1,1,12-06-2013,57,328
55,6260,1955,Master,Together,82384.0,0,0,19-11-2012,55,984
56,10383,1966,Graduation,Divorced,70287.0,0,0,02-04-2013,30,295
57,7437,1988,Graduation,Single,27938.0,1,0,28-04-2014,31,13
58,8557,1982,Graduation,Single,NaN,1,0,17-06-2013,57,11
59,8375,1968,PhD,Married,55954.0,0,1,03-03-2014,63,447
60,6853,1982,Master,Single,75777.0,0,0,04-07-2013,12,712
61,3076,1975,Graduation,Together,66653.0,1,1,07-09-2012,18,452
62,1012,1952,Graduation,Single,61823.0,0,1,18-02-2013,26,523
63,6518,1951,PhD,Widow,67680.0,0,1,11-06-2013,8,546
64,4137,1948,Graduation,Together,70666.0,0,0,06-12-2013,29,398
65,8082,1971,Graduation,Married,25721.0,1,0,21-05-2013,75,1
66,1386,1967,Graduation,Together,32474.0,1,1,11-05-2014,0,10
67,9369,1979,2n Cycle,Single,88194.0,0,1,19-03-2014,19,688
68,4477,1958,Graduation,Together,69096.0,0,1,27-09-2013,4,247
69,1357,1970,Graduation,Together,74854.0,1,2,08-04-2013,90,856
70,1402,1954,Master,Married,66991.0,0,0,11-09-2012,1,496
71,10629,1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25
72,6312,1959,Graduation,Married,65031.0,0,1,17-03-2013,29,258
73,8132,1975,PhD,Married,60631.0,1,1,05-04-2013,88,565
74,1050,1952,Graduation,Married,28332.0,0,0,30-04-2014,58,14
75,5846,1977,Graduation,Divorced,40246.0,1,0,19-12-2012,68,2
76,1859,1972,Master,Married,75251.0,0,0,27-08-2012,34,721
77,7503,1976,Graduation,Single,75825.0,0,0,12-10-2012,40,1032
78,10401,1976,2n Cycle,Together,26326.0,0,0,04-09-2013,12,1
79,1618,1965,Graduation,Together,56046.0,0,0,02-01-2013,9,577
80,3332,1985,Graduation,Single,29760.0,1,0,29-08-2012,87,64
81,2261,1969,Graduation,Married,26304.0,1,0,23-06-2013,5,4
82,5346,1973,2n Cycle,Married,23559.0,1,0,03-07-2013,87,25
83,4119,1963,Master,Together,38620.0,0,0,11-05-2013,56,112
84,535,1987,Graduation,Divorced,81361.0,0,0,25-02-2014,18,163
85,5268,1960,Graduation,Married,29440.0,1,1,11-08-2013,95,17
86,273,1970,Master,Married,36138.0,1,1,16-07-2013,48,130
87,4452,1957,Graduation,Single,50388.0,0,1,28-05-2014,3,292
88,8504,1973,Graduation,Married,79593.0,0,0,12-05-2014,70,350
89,771,1967,Graduation,Together,54178.0,0,1,21-01-2014,79,135
90,8996,1957,PhD,Married,NaN,2,1,19-11-2012,4,230
91,9235,1957,Graduation,Single,NaN,1,1,27-05-2014,45,7
92,5798,1973,Master,Together,NaN,0,0,23-11-2013,87,445
93,11178,1972,Master,Single,42394.0,1,0,23-03-2014,69,15
94,2230,1970,PhD,Married,23626.0,1,0,24-05-2014,84,27
95,7516,1983,Graduation,Married,30096.0,1,0,22-05-2014,30,5
96,7247,1960,Graduation,Widow,47916.0,0,1,22-11-2012,72,505
97,11100,1972,Graduation,Divorced,51813.0,1,1,11-04-2013,37,51
98,4646,1951,2n Cycle,Married,78497.0,0,0,01-12-2013,44,207
99,3037,1983,PhD,Married,50150.0,0,0,20-06-2013,32,135
100,1473,1960,2n Cycle,Single,47823.0,0,1,23-07-2013,0,53
101,1016,1959,PhD,Single,34554.0,0,1,30-03-2014,43,41
102,4518,1979,Graduation,Together,85693.0,0,1,20-04-2013,59,386
103,9370,1945,PhD,Married,65846.0,0,0,17-05-2013,68,562
104,8908,1959,Graduation,Married,87195.0,0,0,08-05-2014,35,217
105,8373,1979,Basic,Together,24594.0,1,0,10-12-2013,94,1
106,7533,1964,Graduation,Married,49096.0,1,1,24-09-2013,15,144
107,2683,1969,Graduation,Married,52413.0,0,2,02-02-2013,56,295
108,3629,1978,Graduation,Single,38557.0,1,0,19-12-2012,17,76
109,10991,1960,Master,Married,89058.0,0,0,07-12-2012,18,454
110,5077,1979,Graduation,Together,77298.0,0,1,02-11-2013,46,425
111,7431,1991,PhD,Single,68126.0,0,0,10-11-2012,40,1332
112,3267,1963,Master,Together,57288.0,0,1,25-06-2014,27,527
113,999,1991,Graduation,Single,86037.0,0,0,02-01-2013,95,490
114,9215,1980,PhD,Married,43974.0,1,0,12-12-2012,19,378
115,2286,1962,Graduation,Single,50785.0,1,1,10-09-2013,27,64
116,1592,1970,Graduation,Married,90765.0,0,0,24-01-2014,25,547
117,367,1978,2n Cycle,Married,36550.0,1,0,19-02-2013,74,47
118,5234,1967,2n Cycle,Together,30753.0,1,1,11-07-2013,85,12
119,9862,1969,Graduation,Together,21918.0,1,0,14-11-2013,37,1
120,9805,1953,Master,Together,56129.0,0,1,20-06-2013,65,320
121,6205,1967,Master,Single,32557.0,1,0,24-02-2014,13,34
122,8442,1985,Master,Married,19510.0,2,0,04-09-2013,63,9
123,7386,1976,Graduation,Divorced,30992.0,1,0,22-04-2013,83,17
124,7215,1983,Graduation,Single,101970.0,0,0,12-03-2013,69,722
125,1491,1965,2n Cycle,Together,71488.0,0,0,18-02-2013,87,162
126,11071,1984,Graduation,Single,79607.0,0,0,21-04-2013,37,450
127,3381,1953,Master,Married,54348.0,1,1,08-06-2014,51,70
128,8268,1961,PhD,Married,NaN,0,1,11-07-2013,23,352
129,11051,1956,PhD,Together,77376.0,1,1,10-05-2014,72,492
130,8026,1952,Graduation,Married,62998.0,0,1,30-09-2013,10,120
131,433,1958,Master,Alone,61331.0,1,1,10-03-2013,42,534
132,9597,1969,Graduation,Married,73448.0,0,0,10-02-2014,10,236
133,1295,1963,Graduation,Married,NaN,0,1,11-08-2013,96,231
134,5290,1964,PhD,Married,41551.0,1,1,14-08-2013,51,220
135,1685,1967,PhD,Together,62981.0,0,0,17-03-2013,21,796
136,5342,1976,Basic,Divorced,9548.0,1,0,08-08-2012,31,0
137,9579,1959,PhD,Married,33762.0,2,1,07-07-2013,61,53
138,7660,1973,PhD,Alone,35860.0,1,1,19-05-2014,37,15
139,1461,1965,PhD,Divorced,36921.0,1,1,28-07-2013,74,17
140,821,1992,Master,Single,92859.0,0,0,19-10-2012,46,962
141,11084,1976,Master,Together,65104.0,0,1,14-11-2013,4,738
142,8690,1962,Graduation,Married,86111.0,0,0,19-04-2013,73,399
143,2937,1974,PhD,Single,68352.0,0,1,28-08-2013,47,614
144,9701,1988,Graduation,Together,41883.0,1,0,19-03-2013,13,32
145,9949,1976,Graduation,Married,59809.0,0,2,18-10-2012,36,598
146,10837,1975,Graduation,Married,23957.0,1,0,28-10-2012,47,2
147,3120,1981,Graduation,Together,38547.0,1,0,28-08-2013,49,6
148,5885,1973,2n Cycle,Married,35688.0,2,1,22-08-2012,94,73
149,4050,1966,Master,Married,49605.0,0,0,21-06-2014,65,42
150,3830,1953,Master,Married,59354.0,0,2,24-04-2014,59,295
151,7987,1969,Graduation,Married,65747.0,0,1,07-03-2014,96,346
152,7798,1972,2n Cycle,Together,46344.0,0,1,14-12-2012,28,233
153,92,1988,Graduation,Alone,34176.0,1,0,12-05-2014,12,5
154,7055,1952,PhD,Together,61010.0,0,1,09-10-2012,57,888
155,10240,1949,Graduation,Together,69372.0,0,0,19-02-2013,10,997
156,3025,1958,Graduation,Single,49967.0,0,1,08-07-2013,4,212
157,9283,1978,Graduation,Single,60199.0,1,2,12-09-2013,49,8
158,9970,1977,Graduation,Together,55375.0,0,1,17-10-2013,3,42
159,2730,1955,Graduation,Single,80317.0,0,0,20-08-2013,64,536
160,2795,1958,Master,Single,30523.0,2,1,01-07-2013,0,5
161,9260,1945,PhD,Married,70356.0,0,0,05-11-2012,20,1349
162,8182,1984,Graduation,Married,23228.0,1,0,05-01-2014,91,53
163,10095,1975,PhD,Divorced,74165.0,0,0,01-05-2013,9,1001
164,8475,1973,PhD,Married,157243.0,0,1,01-03-2014,98,20
165,4370,1966,Graduation,Together,43482.0,2,1,13-11-2013,83,18
166,10573,1953,Graduation,Divorced,62551.0,0,0,18-11-2013,27,125
167,3712,1959,Graduation,Divorced,52332.0,0,0,28-08-2013,63,212
168,6637,1988,Graduation,Single,66951.0,0,0,02-11-2013,46,277
169,3152,1957,Graduation,Together,26091.0,1,1,25-02-2014,84,15
170,5610,1965,Graduation,Together,33456.0,1,1,21-04-2014,58,7
171,6460,1982,Graduation,Married,28718.0,1,0,13-07-2013,78,12
172,1349,1970,Graduation,Married,50447.0,2,0,21-04-2014,4,85
173,1880,1959,PhD,Together,53537.0,1,1,30-01-2014,17,81
174,641,1967,Graduation,Single,52074.0,0,1,04-04-2014,77,59
175,8717,1975,PhD,Married,80427.0,0,1,12-09-2012,56,1149
176,10314,1948,PhD,Married,83837.0,0,0,16-12-2012,79,847
177,10854,1970,PhD,Married,38853.0,1,1,23-05-2014,90,29
178,10492,1959,Graduation,Together,38285.0,2,1,24-06-2014,96,2
179,6935,1951,2n Cycle,Married,78497.0,0,0,01-12-2013,44,207
180,7698,1976,PhD,Married,51650.0,0,1,11-05-2014,81,152
181,3559,1988,2n Cycle,Married,16248.0,1,0,10-05-2014,77,12
182,10562,1946,Master,Married,66835.0,0,0,28-09-2013,21,620
183,10796,1984,Master,Married,30477.0,1,0,22-01-2014,16,47
184,2563,1961,Basic,Married,28249.0,0,0,15-06-2014,80,1
185,3518,1983,Graduation,Married,25271.0,1,0,05-12-2012,45,10
186,5823,1970,PhD,Single,32303.0,0,1,08-03-2014,63,35
187,3934,1966,Graduation,Married,61286.0,0,1,02-08-2013,34,356
188,6982,1976,Graduation,Married,74068.0,0,0,19-03-2013,14,783
189,6431,1964,PhD,Married,45759.0,1,1,23-02-2013,13,42
190,9733,1978,Basic,Together,24882.0,1,0,09-09-2012,52,1
191,5602,1989,PhD,Together,66973.0,0,0,17-05-2013,98,466
192,7829,1900,2n Cycle,Divorced,36640.0,1,0,26-09-2013,99,15
193,1324,1988,Graduation,Married,38872.0,1,0,30-05-2013,93,23
194,326,1973,Graduation,Married,51148.0,1,1,18-02-2013,38,235
195,7224,1977,Graduation,Married,31353.0,1,1,29-12-2013,24,10
196,6999,1980,Master,Married,69661.0,0,0,13-05-2014,80,656
197,9938,1954,Graduation,Married,80067.0,0,0,19-09-2013,82,519
198,6422,1954,Graduation,Married,86718.0,0,0,17-01-2013,20,344
199,3182,1973,PhD,Single,46854.0,1,1,31-03-2014,81,96
200,7300,1952,Graduation,Divorced,69142.0,0,1,29-06-2014,50,448
201,10424,1968,Graduation,Single,75922.0,0,0,09-12-2013,60,265
202,8727,1978,Graduation,Divorced,63693.0,0,1,14-10-2013,63,587
203,2798,1977,PhD,Together,102160.0,0,0,02-11-2012,54,763
204,1030,1965,PhD,Single,40637.0,1,1,17-07-2013,72,22
205,624,1984,Master,Single,18890.0,0,0,10-11-2012,5,6
206,5176,1988,Graduation,Together,29604.0,1,0,08-12-2013,88,7
207,5552,1963,Master,Divorced,48721.0,1,1,13-05-2013,50,81
208,868,1966,Graduation,Married,44794.0,0,1,08-06-2014,99,54
209,380,1954,Graduation,Divorced,64497.0,0,1,10-09-2012,17,1170
210,2677,1956,Graduation,Together,46097.0,0,1,31-03-2013,11,72
211,6521,1954,Graduation,Together,77972.0,0,0,18-03-2014,18,613
212,6927,1968,PhD,Married,44377.0,1,1,05-10-2012,70,224
213,2877,1974,Master,Together,46014.0,1,1,21-01-2013,21,410
214,0,1985,Graduation,Married,70951.0,0,0,04-05-2013,66,239
215,1584,1977,Graduation,Married,41443.0,1,0,01-04-2014,79,171
216,7264,1978,2n Cycle,Single,52195.0,2,1,12-05-2014,2,12
217,6274,1948,Master,Married,83790.0,0,0,15-11-2013,81,1076
218,1377,1954,Master,Widow,44551.0,0,1,31-08-2013,24,182
219,454,1980,Graduation,Together,69508.0,1,0,14-11-2012,48,824
220,1755,1988,2n Cycle,Together,45204.0,1,0,11-04-2014,93,30
221,2075,1969,Graduation,Married,72460.0,0,0,14-11-2013,56,377
222,4785,1970,PhD,Together,77622.0,0,2,14-04-2014,3,520
223,9076,1980,PhD,Married,30732.0,1,0,05-01-2013,44,155
224,7079,1962,Graduation,Divorced,63887.0,0,1,08-09-2012,38,897
225,4653,1978,Graduation,Together,42011.0,1,0,26-03-2013,46,131
226,7375,1976,Graduation,Together,51369.0,0,1,25-10-2012,84,297
227,709,1952,Graduation,Divorced,51537.0,0,1,09-12-2012,27,787
228,460,1972,PhD,Married,79930.0,0,0,08-08-2012,72,792
229,3726,1986,PhD,Together,34320.0,1,0,16-02-2014,66,4
230,6798,1966,Graduation,Single,37070.0,1,1,20-03-2013,30,231
231,5341,1962,2n Cycle,Divorced,81975.0,0,1,05-01-2013,2,983
232,1606,1971,Graduation,Together,38590.0,1,0,15-05-2013,65,3
233,9617,1951,Graduation,Single,15033.0,0,0,16-04-2014,37,0
234,3233,1965,PhD,Married,62745.0,0,1,23-03-2013,89,562
235,89,1975,2n Cycle,Married,22212.0,1,0,09-12-2013,49,5
236,2936,1982,Master,Together,23661.0,1,0,04-12-2013,46,18
237,9449,1958,PhD,Single,79761.0,0,1,04-10-2013,32,415
238,7297,1973,Graduation,Single,7500.0,1,0,26-12-2013,54,5
239,11004,1893,2n Cycle,Single,60182.0,0,1,17-05-2014,23,8
240,313,1968,Graduation,Widow,73455.0,0,0,28-10-2013,98,901
241,9940,1958,Graduation,Together,64961.0,0,1,23-12-2012,97,382
242,10735,1971,Graduation,Single,22804.0,1,0,31-07-2013,75,14
243,9529,1990,Graduation,Married,73687.0,0,0,28-11-2013,8,559
244,6439,1958,Graduation,Married,61074.0,0,1,17-08-2012,37,789
245,7411,1964,PhD,Married,31686.0,1,1,05-06-2014,31,11
246,2176,1972,Graduation,Married,80134.0,1,0,20-05-2013,40,1218
247,9265,1953,Graduation,Married,75027.0,0,1,09-01-2013,74,925
248,8867,1988,PhD,Married,67546.0,0,0,31-08-2012,90,864
249,8932,1969,Master,Together,65176.0,0,1,29-10-2012,57,960
250,10236,1975,Master,Single,31160.0,1,0,16-09-2013,59,16
251,6340,1985,Graduation,Single,29938.0,1,0,27-10-2013,52,3
252,10089,1974,Graduation,Divorced,102692.0,0,0,05-04-2013,5,168
253,2227,1958,2n Cycle,Together,26490.0,0,0,22-09-2012,92,45
254,10992,1967,Graduation,Together,75702.0,1,1,29-08-2012,77,650
255,5304,1974,PhD,Single,30899.0,1,0,13-10-2012,35,24
256,309,1961,PhD,Together,63342.0,0,1,16-10-2012,48,918
257,3406,1964,Graduation,Single,45989.0,0,1,22-10-2012,97,138
258,2661,1964,Graduation,Single,18701.0,1,1,04-06-2013,95,12
259,3153,1957,PhD,Single,40737.0,2,1,08-12-2013,24,11
260,10264,1979,Graduation,Divorced,15287.0,1,0,10-10-2012,60,1
261,1184,1968,PhD,Divorced,69674.0,0,2,22-05-2013,46,554
262,4200,1970,Master,Married,44159.0,1,0,17-06-2014,85,167
263,9396,1978,PhD,Married,37717.0,1,0,23-11-2012,31,9
264,2387,1952,Master,Together,43776.0,1,1,03-02-2013,9,177
265,6690,1966,Master,Married,38179.0,1,1,14-03-2013,30,38
266,1225,1963,Graduation,Married,80124.0,0,0,26-06-2014,47,483
267,9703,1970,PhD,Married,38097.0,1,1,15-10-2012,70,77
268,291,1970,Graduation,Married,72940.0,0,0,19-06-2013,13,182
269,4557,1970,Graduation,Together,22070.0,1,0,04-10-2013,11,10
270,2379,1953,Graduation,Single,69267.0,0,0,22-09-2012,31,778
271,5726,1983,Master,Single,31788.0,1,0,20-03-2014,15,16
272,3066,1975,PhD,Together,61905.0,0,1,04-02-2014,2,167
273,6336,1960,Graduation,Married,29315.0,1,1,06-04-2014,55,13
274,10967,1963,Graduation,Divorced,33378.0,1,1,06-02-2013,38,33
275,2304,1963,PhD,Together,66313.0,0,1,16-09-2013,86,625
276,3445,1956,Graduation,Single,60714.0,0,0,17-01-2013,56,216
277,7828,1981,Master,Together,77882.0,0,0,30-04-2014,29,68
278,3762,1986,PhD,Single,69867.0,0,0,02-04-2013,30,196
279,4391,1968,Master,Divorced,63841.0,0,1,21-04-2013,64,635
280,4669,1981,Basic,Married,24480.0,1,0,11-02-2013,46,4
281,10144,1976,Graduation,Together,51369.0,0,1,25-10-2012,84,297
282,8652,1946,Graduation,Together,37760.0,0,0,31-08-2012,20,84
283,1672,1974,PhD,Together,65640.0,0,1,01-03-2014,74,204
284,8962,1975,Master,Married,44319.0,1,1,17-04-2014,18,26
285,9974,1974,Graduation,Married,30631.0,1,0,12-07-2013,75,15
286,10983,1952,Graduation,Together,75278.0,0,0,29-01-2013,17,304
287,8148,1956,Master,Together,50898.0,1,1,08-01-2013,88,285
288,10102,1966,Graduation,Widow,79946.0,0,0,12-05-2014,19,395
289,4697,1949,Master,Divorced,35416.0,0,0,13-06-2013,62,248
290,9262,1984,2n Cycle,Together,32414.0,0,0,04-07-2013,11,20
291,7254,1969,Graduation,Together,38361.0,1,0,27-12-2013,74,39
292,4543,1980,Graduation,Married,82497.0,0,0,31-10-2012,32,777
293,4927,1971,Graduation,Together,16626.0,2,0,15-01-2014,76,8
294,10451,1965,Graduation,Together,29672.0,1,1,12-03-2013,6,9
295,2926,1952,Master,Together,55951.0,0,1,23-08-2012,62,1241
296,2874,1988,2n Cycle,Divorced,35388.0,1,0,07-03-2013,20,6
297,9738,1986,Master,Together,42386.0,1,0,13-01-2013,43,65
298,7119,1982,Graduation,Single,68627.0,0,0,12-01-2013,45,395
299,3924,1965,PhD,Divorced,57912.0,0,1,17-03-2014,34,801
300,5827,1958,Graduation,Divorced,35246.0,1,1,16-04-2014,53,36
301,5596,1956,2n Cycle,Together,58821.0,0,1,12-10-2013,44,513
302,10812,1978,PhD,Married,46377.0,1,0,01-03-2014,89,37
303,1717,1988,Graduation,Single,39747.0,1,0,13-04-2014,43,80
304,9491,1984,Graduation,Together,23976.0,1,0,27-12-2013,68,14
305,9274,1961,Master,Married,80950.0,0,0,28-03-2013,44,525
306,6609,1966,Graduation,Widow,27038.0,0,0,18-09-2012,64,1
307,6963,1947,Graduation,Single,77457.0,0,0,05-03-2014,85,675
308,4440,1964,Master,Married,64100.0,0,1,10-09-2013,93,509
309,1379,1992,Master,Together,42670.0,0,0,27-04-2013,12,154
310,10032,1976,Graduation,Divorced,12571.0,1,0,18-01-2014,86,3
311,2826,1967,Graduation,Married,22574.0,2,1,28-10-2013,28,25
312,2437,1989,Graduation,Married,NaN,0,0,03-06-2013,69,861
313,6320,1976,Master,Single,70893.0,0,0,06-02-2013,42,768
314,3050,1966,Graduation,Married,54198.0,1,1,17-12-2013,13,185
315,231,1956,Master,Together,28839.0,1,1,11-03-2014,86,24
316,2392,1972,Graduation,Married,40321.0,1,1,29-07-2013,59,44
317,9478,1985,Graduation,Single,66503.0,1,0,14-08-2012,30,91
318,113,1951,Graduation,Married,30833.0,1,1,16-07-2013,33,11
319,2863,1970,Graduation,Single,NaN,1,2,23-08-2013,67,738
320,1802,1971,Graduation,Married,64795.0,0,1,17-01-2013,23,412
321,520,1974,Graduation,Married,34421.0,1,0,01-07-2013,81,3
322,8275,1965,PhD,Divorced,47025.0,1,1,09-02-2014,6,16
323,9750,1961,PhD,Divorced,64325.0,0,1,07-02-2013,41,731
324,2607,1953,Graduation,Single,40464.0,0,1,11-01-2013,78,424
325,7214,1957,Graduation,Married,62187.0,0,0,05-07-2013,49,792
326,5835,1976,PhD,Divorced,14849.0,1,0,02-07-2013,39,21
327,3896,1984,Graduation,Married,27255.0,1,0,07-11-2013,3,22
328,10350,1950,PhD,Married,54432.0,2,1,09-05-2013,37,33
329,7786,1986,PhD,Single,29999.0,1,0,13-02-2013,22,68
330,2861,1983,Graduation,Single,24072.0,1,0,16-04-2013,79,9
331,663,1989,PhD,Single,33996.0,0,0,11-09-2013,46,40
332,10675,1956,PhD,Married,66334.0,0,1,03-04-2013,82,909
333,2521,1971,Master,Married,35178.0,1,0,10-01-2013,10,23

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              2240 non-null   int64
 1   Year_Birth      2240 non-null   int64
 2   Education       2240 non-null   object
 3   Marital_Status  2240 non-null   object
 4   Income          2216 non-null   float64
 5   Kidhome         2240 non-null   int64
 6   Teenhome        2240 non-null   int64
 7   Dt_Customer     2240 non-null   object
 8   Recency         2240 non-null   int64
 9   MntWines        2240 non-null   int64
dtypes: float64(1), int64(6), object(3)
memory usage: 175.1+ KB

In [16]:
df.isnull().sum()

ID                 0
Year_Birth         0
Education          0
Marital_Status     0
Income            24
Kidhome            0
Teenhome           0
Dt_Customer        0
Recency            0
MntWines           0
dtype: int64

In [18]:
df.columns = df.columns.str.lower().str.replace("year_birth", "marital_status")

In [20]:
df['income'] = df['income'].fillna(df['income'].mean())

In [21]:
df.isnull().sum()

id                0
marital_status    0
education         0
marital_status    0
income            0
kidhome           0
teenhome          0
dt_customer       0
recency           0
mntwines          0
dtype: int64

In [22]:
df['dt_customer'] = pd.to_datetime(df['dt_customer'], errors='coerce')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2240 non-null   int64
 1   marital_status  2240 non-null   int64
 2   education       2240 non-null   object
 3   marital_status  2240 non-null   object
 4   income          2240 non-null   float64
 5   kidhome         2240 non-null   int64
 6   teenhome        2240 non-null   int64
 7   dt_customer     916 non-null    datetime64[ns]
 8   recency         2240 non-null   int64
 9   mntwines        2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 175.1+ KB

In [24]:
df = df.dropna(subset=['dt_customer'])

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df['marital_status'] = df['marital_status'].replace({'Together': 'Partner'})

In [27]:
df.to_csv("cleaned_customer_data.csv", index=False)

In [28]:
df.shape

(916, 10)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 916 entries, 0 to 2236
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              916 non-null    int64
 1   marital_status  916 non-null    int64
 2   education       916 non-null    object
 3   marital_status  916 non-null    object
 4   income          916 non-null    float64
 5   kidhome         916 non-null    int64
 6   teenhome        916 non-null    int64
 7   dt_customer     916 non-null    datetime64[ns]
 8   recency         916 non-null    int64
 9   mntwines        916 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 78.7+ KB

In [30]:
df.isnull().sum()

id                0
marital_status    0
education         0
marital_status    0
income            0
kidhome           0
teenhome          0
dt_customer       0
recency           0
mntwines          0
dtype: int64

In [34]:
df = df.dropna(subset=['dt_customer'])

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.isnull().sum()

id                0
marital_status    0
education         0
marital_status    0
income            0
kidhome           0
teenhome          0
dt_customer       0
recency           0
mntwines          0
dtype: int64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 916 entries, 0 to 2236
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              916 non-null    int64
 1   marital_status  916 non-null    int64
 2   education       916 non-null    object
 3   marital_status  916 non-null    object
 4   income          916 non-null    float64
 5   kidhome         916 non-null    int64
 6   teenhome        916 non-null    int64
 7   dt_customer     916 non-null    datetime64[ns]
 8   recency         916 non-null    int64
 9   mntwines        916 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 78.7+ KB

In [38]:
df.columns

Index(['id', 'marital_status', 'education', 'marital_status', 'income',
       'kidhome', 'teenhome', 'dt_customer', 'recency', 'mntwines'],
      dtype='object')

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.shape

(916, 10)

In [41]:
df.to_csv("cleaned_customer_data.csv", index=False)